package tablas;
// Generated 18-mar-2019 21:54:18 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;





/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria")
public class Categoria implements Serializable {
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name="idcategoria")
	private int idcategoria;
	@Column(name="nombreCategoria")
	private String nombreCategoria;
	//categoria es de la class Articulo Categoria categoria
	@OneToMany(mappedBy ="categoria",cascade=CascadeType.ALL)
	private List<Articulo> articulos = new ArrayList<>();

	public Categoria() {
		super();
	}

	public Categoria(String nombreCategoria) {
		super();
		this.nombreCategoria = nombreCategoria;
	}

	public Categoria(String nombreCategoria, List articulos) {
		super();
		this.nombreCategoria = nombreCategoria;
		this.articulos = articulos;
		
	}
	public Categoria(int idcategoria, String nombreCategoria) {
		super();
		this.idcategoria = idcategoria;
		this.nombreCategoria = nombreCategoria;
	}
	
	public void addArticulo(Articulo articulo) {
		if(!articulos.contains(articulo)) {
			articulos.add(articulo);
			articulo.setCategoria(this);
		}
			
	}
	
	public List<Articulo> getArticulos(){
		return articulos;
	}
	
	public void setArticulos(List<Articulo> articulos) {
		this.articulos = articulos;
	}

	public int getIdcategoria() {
		return idcategoria;
	}

	public void setIdcategoria(int idcategoria) {
		this.idcategoria = idcategoria;
	}

	public String getNombreCategoria() {
		return nombreCategoria;
	}

	public void setNombreCategoria(String nombreCategoria) {
		this.nombreCategoria = nombreCategoria;
	}
	

}
