package tablas;

// Generated 10-mar-2019 11:47:42 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente")
public class Cliente extends Sociedad implements Serializable   {
	private static final long serialVersionUID = 1L;

	public Cliente() {
	}
	public Cliente(String denominacion, String domicilio, String email,
			String poblacion, String provincia, int codigoPostal,int id,Usuario usuarios,
			int telefono) {
		super(denominacion,domicilio,email,poblacion,provincia,codigoPostal,id,usuarios,telefono);
	}

	public Cliente(String denominacion, String domicilio, String email,
			String poblacion, String provincia, int codigoPostal,int id,
			int telefono) {
		super(denominacion,domicilio,email,poblacion,provincia,codigoPostal,id,telefono);
	}
}
