package tablas;

// Generated 10-mar-2019 11:47:42 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * CustomerLineItems generated by hbm2java
 */
public class CustomerLineItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idcustomerLineItems;
	private CustomerInvoices customerInvoices;
	private Articulo articulo;
	private Integer cantidadVendida;
	private Integer taxRate;
	private BigDecimal precioVenta;

	public CustomerLineItems() {
	}

	public CustomerLineItems(CustomerInvoices customerInvoices,
			Articulo articulo) {
		this.customerInvoices = customerInvoices;
		this.articulo = articulo;
	}

	public CustomerLineItems(CustomerInvoices customerInvoices,
			Articulo articulo, Integer cantidadVendida, Integer taxRate,
			BigDecimal precioVenta) {
		this.customerInvoices = customerInvoices;
		this.articulo = articulo;
		this.cantidadVendida = cantidadVendida;
		this.taxRate = taxRate;
		this.precioVenta = precioVenta;
	}

	public Integer getIdcustomerLineItems() {
		return this.idcustomerLineItems;
	}

	public void setIdcustomerLineItems(Integer idcustomerLineItems) {
		this.idcustomerLineItems = idcustomerLineItems;
	}

	public CustomerInvoices getCustomerInvoices() {
		return this.customerInvoices;
	}

	public void setCustomerInvoices(CustomerInvoices customerInvoices) {
		this.customerInvoices = customerInvoices;
	}

	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	public Integer getCantidadVendida() {
		return this.cantidadVendida;
	}

	public void setCantidadVendida(Integer cantidadVendida) {
		this.cantidadVendida = cantidadVendida;
	}

	public Integer getTaxRate() {
		return this.taxRate;
	}

	public void setTaxRate(Integer taxRate) {
		this.taxRate = taxRate;
	}

	public BigDecimal getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(BigDecimal precioVenta) {
		this.precioVenta = precioVenta;
	}

}
