package tablas;

import java.io.Serializable;
import java.sql.Date;

// Generated 10-mar-2019 11:47:42 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierInvoices generated by hbm2java
 */
public class SupplierInvoices implements Serializable {

	private static final long serialVersionUID = 1L;
	private int idSupplierInvoices;
	private Proveedor proveedor;
	private Date fecha;
	private int numeroFactura;
	private Set supplierInvoiceLineItemses = new HashSet(0);

	public SupplierInvoices() {
		super();
	}

	public SupplierInvoices(Proveedor proveedor) {
		this.proveedor = proveedor;
	}
	
	public SupplierInvoices(int idSupplierInvoices) {
		this.idSupplierInvoices=idSupplierInvoices;
	}
	
	
	public SupplierInvoices(int idSupplierInvoices, Proveedor proveedor, Date fecha, int numeroFactura,
			Set supplierInvoiceLineItemses) {
		super();
		this.idSupplierInvoices = idSupplierInvoices;
		this.proveedor = proveedor;
		this.fecha = fecha;
		this.numeroFactura = numeroFactura;
		this.supplierInvoiceLineItemses = supplierInvoiceLineItemses;
	}
	public SupplierInvoices(Proveedor proveedor, Date fecha,
			Set supplierInvoiceLineItemses) {
		this.proveedor = proveedor;
		this.fecha = fecha;
		this.supplierInvoiceLineItemses = supplierInvoiceLineItemses;
	}

	public int getNumeroFactura() {
		return numeroFactura;
	}

	public void setNumeroFactura(int numeroFactura) {
		this.numeroFactura = numeroFactura;
	}



	public int getIdSupplierInvoices() {
		return this.idSupplierInvoices;
	}

	public void setIdSupplierInvoices(int idSupplierInvoices) {
		this.idSupplierInvoices = idSupplierInvoices;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set getSupplierInvoiceLineItemses() {
		return this.supplierInvoiceLineItemses;
	}

	public void setSupplierInvoiceLineItemses(Set supplierInvoiceLineItemses) {
		this.supplierInvoiceLineItemses = supplierInvoiceLineItemses;
	}

}
