package tablas;

// Generated 10-mar-2019 11:47:42 by Hibernate Tools 3.4.0.CR1



/**
 * SupplierInvoiceLineItems generated by hbm2java
 */
public class SupplierInvoiceLineItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idsupplierInvoiceLineItems;
	private Articulo articulo;
	private SupplierInvoices supplierInvoices;
	private Integer cantidadComprada;
	private Integer taxRateCharged;
	private Double precioCompra;

	public SupplierInvoiceLineItems() {
	}

	public SupplierInvoiceLineItems(Articulo articulo,
			SupplierInvoices supplierInvoices) {
		this.articulo = articulo;
		this.supplierInvoices = supplierInvoices;
	}

	public SupplierInvoiceLineItems(Articulo articulo,
			SupplierInvoices supplierInvoices, Integer cantidadComprada,
			Integer taxRateCharged, Double precioCompra) {
		this.articulo = articulo;
		this.supplierInvoices = supplierInvoices;
		this.cantidadComprada = cantidadComprada;
		this.taxRateCharged = taxRateCharged;
		this.precioCompra = precioCompra;
	}

	public Integer getIdsupplierInvoiceLineItems() {
		return this.idsupplierInvoiceLineItems;
	}

	public void setIdsupplierInvoiceLineItems(Integer idsupplierInvoiceLineItems) {
		this.idsupplierInvoiceLineItems = idsupplierInvoiceLineItems;
	}

	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	public SupplierInvoices getSupplierInvoices() {
		return this.supplierInvoices;
	}

	public void setSupplierInvoices(SupplierInvoices supplierInvoices) {
		this.supplierInvoices = supplierInvoices;
	}

	public Integer getCantidadComprada() {
		return this.cantidadComprada;
	}

	public void setCantidadComprada(Integer cantidadComprada) {
		this.cantidadComprada = cantidadComprada;
	}

	public Integer getTaxRateCharged() {
		return this.taxRateCharged;
	}

	public void setTaxRateCharged(Integer taxRateCharged) {
		this.taxRateCharged = taxRateCharged;
	}

	public Double getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(Double precioCompra) {
		this.precioCompra = precioCompra;
	}

}
